# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - releases/*
    exclude:
    - master

stages:
- stage: Bazel_Build
  displayName: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps: 
    - script: |
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y bazel
      displayName: 'install bazel'

    - script: |
        bazel version
      displayName: 'show bazel version'

    - script: |
        cd bazel-hello
        bazel clean 
      displayName: 'clean project' 

    - script: |
        cd bazel-hello
        bazel build ... 
      displayName: 'run all build'  

- stage: Bazel_Tests
  displayName: Test
  jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-latest'

    steps:  
    - script: |
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y bazel
      displayName: 'install bazel'

    - script: |
        bazel version
      displayName: 'show bazel version'

    - script: |
        cd bazel-hello
        bazel test ... 
      displayName: 'run all tests'

   
